import React from 'react';
import { motion } from 'framer-motion';
import { ShieldAlert, ArrowLeft } from 'lucide-react';
import { useNavigate } from 'react-router-dom';

export default function Terms() {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen p-4 md:p-8 lg:p-16 max-w-4xl mx-auto">
      <button onClick={() => navigate(-1)} className="flex items-center gap-2 text-gray-400 hover:text-white transition-colors text-sm mb-8">
        <ArrowLeft size={18} /> Back
      </button>

      <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}>
        <div className="flex items-center gap-3 mb-6">
          <ShieldAlert className="text-neon-green" size={32} />
          <h1 className="text-3xl md:text-4xl font-bold text-white">Terms of Service</h1>
        </div>
        <p className="text-gray-500 text-sm mb-8">Last Updated: April 28, 2026</p>

        <div className="space-y-8 text-gray-300 leading-relaxed text-sm md:text-base">
          <section>
            <h2 className="text-xl font-semibold text-white mb-3">1. Acceptance of Terms</h2>
            <p>By accessing or using the Bhasha-Verify platform ("Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our Service.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">2. Description of Service</h2>
            <p>Bhasha-Verify provides an AI-powered scam detection tool designed to analyze text messages, URLs, and audio recordings for potential phishing, fraud, or spoofing attempts. The Service is intended for educational and personal security awareness purposes only.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">3. No Legal or Professional Advice</h2>
            <p>The analysis provided by Bhasha-Verify is generated by Artificial Intelligence algorithms. While we strive for high accuracy, the results are <strong className="text-white">not guaranteed</strong> to be 100% accurate. The Service does not constitute legal, financial, or professional cybersecurity advice. You should always exercise your own judgment before interacting with suspicious messages or links.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">4. User Responsibilities</h2>
            <ul className="list-disc list-inside space-y-2 ml-2">
              <li>You agree not to use the Service for any unlawful or unauthorized purpose.</li>
              <li>You agree not to submit any classified, legally privileged, or highly sensitive confidential information that you are not authorized to share.</li>
              <li>You are responsible for maintaining the confidentiality of your account credentials.</li>
              <li>You agree not to attempt to reverse engineer, disrupt, or attack the Service or its underlying infrastructure.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">5. Disclaimer of Warranties</h2>
            <p>The Service is provided on an "AS IS" and "AS AVAILABLE" basis. We disclaim all warranties of any kind, whether express or implied, including but not limited to the implied warranties of merchantability, fitness for a particular purpose, and non-infringement. We do not warrant that the Service will be uninterrupted, timely, secure, or error-free.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">6. Limitation of Liability</h2>
            <p>In no event shall Bhasha-Verify or its developers be liable for any direct, indirect, incidental, special, consequential, or exemplary damages, including but not limited to financial loss resulting from a scam or fraud, even if we have been advised of the possibility of such damages, arising out of or in connection with the use or inability to use the Service.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">7. Modifications to the Service</h2>
            <p>We reserve the right to modify, suspend, or discontinue, temporarily or permanently, the Service (or any part thereof) with or without notice at any time. We may also update these Terms from time to time. Your continued use of the Service after any modifications indicates your acceptance of the updated Terms.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">8. Contact</h2>
            <p>For any questions regarding these Terms, please contact us at: <a href="mailto:ayushvishwakarmadto29@gmail.com" className="text-neon-green hover:underline">ayushvishwakarmadto29@gmail.com</a></p>
          </section>
        </div>
      </motion.div>
    </div>
  );
}
